version: "3.7"

services:
  forticlient:
    build:
      context: .
      dockerfile: Dockerfile
    image: hybirdcorp/docker-forticlient
    environment:
      - VPNADDR=VPN01.pickup-services.com
      - VPNUSER=m.partensky@pickup-services.com
      - VPNPASS=69GlouGlou69
      - VPNTIMEOUT=30
    network_mode: "host"
    privileged: true
